name: "CI for builds"

on:
  push:
    tags:
      - 'v*'

jobs:
  build-amd64:
    name: amd64-${{ matrix.libc }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - container: golang:1.19-bullseye
            libc: glibc
          - container: golang:1.19-alpine
            libc: musl

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: go build -ldflags="-s -w"

      - name: Upload to releases
        uses: svenstaro/upload-release-action@v2
        id: attach_to_release
        with:
          file: go-transcode
          asset_name: go-transcode-amd64-${{ matrix.libc }}
          tag: ${{ github.ref }}
          overwrite: true
